apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  JWT_USERTOKEN: "replace_with_a_long_random_secretss"
  MONGODB_URL: "mongodb://admin:mypassword123@mongo:27017/nestly?authSource=admin"