- name: deploy kubernetes resources
  hosts: vm
  become: yes

  tasks:
    - name: Apply mongo-secrets
      command:  kubectl apply -f /home/ubuntu/mongo-secret.yaml
      
    - name: Apply secrets
      command: kubectl apply -f /home/ubuntu/secrets.yaml

    - name: Apply configmap
      command: kubectl apply -f /home/ubuntu/configmap.yaml

    - name: Apply MongoDB resources
      command: kubectl apply -f .
      args:
        chdir: /home/ubuntu/mongodb

    - name: Wait for MongoDB rollout
      command: kubectl rollout status statefulset mongo

    - name: Apply backend resources
      command: kubectl apply -f .
      args:
        chdir: /home/ubuntu/backend

    - name: Restart backend deployment
      command: kubectl rollout restart deployment backend-deployment

    - name: Wait for backend rollout
      command: kubectl rollout status deployment backend-deployment

    - name: Apply frontend resources
      command: kubectl apply -f .
      args:
        chdir: /home/ubuntu/frontend

    - name: Restart frontend deployment
      command: kubectl rollout restart deployment frontend-deployment

    - name: Wait for frontend rollout
      command: kubectl rollout status deployment frontend-deployment