---
- name: Setup Docker and Kind
  hosts: vm
  become: yes
  gather_facts: yes
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg
          - socat
        state: present

    - name: Create directory for Docker GPG key
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker APT repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Install Docker components
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Ensure Docker is started and enabled
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Add user ubuntu to docker group
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Download and install kind
      ansible.builtin.get_url:
        url: "https://kind.sigs.k8s.io/dl/v0.22.0/kind-linux-amd64"
        dest: /usr/local/bin/kind
        mode: '0755'


    - name: Download and install kompose
      ansible.builtin.get_url:
        url: "https://github.com/kubernetes/kompose/releases/download/v1.38.0/kompose-linux-amd64"
        dest: /usr/local/bin/kompose
        mode: '0755'  
    
    - name: Download and install kubectl
      ansible.builtin.get_url:
        url: "https://dl.k8s.io/release/v1.35.0/bin/linux/amd64/kubectl"
        dest: /usr/local/bin/kubectl
        mode: '0755'

    - name: Download and install cloude provider kind
      ansible.builtin.get_url:
        url: "https://github.com/kubernetes-sigs/cloud-provider-kind/releases/download/v0.10.0/cloud-provider-kind_0.10.0_linux_amd64.tar.gz"
        dest: /home/ubuntu/
        mode: '0755'

    - name: extract and move cloud provider kind to /usr/local/bin
      shell: |
        tar -xvf cloud-provider-kind_0.10.0_linux_amd64.tar.gz
        sudo mv cloud-provider-kind /usr/local/bin
      args:
        chdir: /home/ubuntu/